apiVersion: batch/v1
kind: Job
metadata:
  name: windows-exporter-installer
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      annotations:
      labels:
        {{- include "opentelemetry-collector.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "opentelemetry-collector.serviceAccountName" . }}
      containers:
        - name: windows-exporter-installer
          image: "tamirmich/windows-exporter-installer:latest"
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: logzio-windows-exporter-installer-secrets
                  key: windowsNodeUsername
                  optional: true
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logzio-windows-exporter-installer-secrets
                  key: windowsNodePassword
                  optional: true
          args:  ["$(SECRET_USERNAME)",
                 "$(SECRET_PASSWORD)"]
          securityContext:
            privileged: true
      nodeSelector:
        kubernetes.io/os: linux
