sudo: required
dist: trusty
language: ruby
before_install:
  - gem update --system --no-doc
  - gem install bundler --no-doc
  - gem update bundler --no-doc
rvm:
  - 2.5.0
  - 2.4.2
  - 2.3.5
  - 2.2.8
gemfile:
  - gemfiles/Gemfile.rails-5.1.x
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.0.x
matrix:
  exclude:
    # Rails 5+ only on MRI 2.3+
    - { rvm: "2.2.8", gemfile: "gemfiles/Gemfile.rails-5.1.x" }
    - { rvm: "2.2.8", gemfile: "gemfiles/Gemfile.rails-5.0.x" }

    # Rails < 5 not on MRI 2.4
    - { rvm: "2.4.2", gemfile: "gemfiles/Gemfile.rails-4.2.x" }
    - { rvm: "2.4.2", gemfile: "gemfiles/Gemfile.rails-4.1.x" }
    - { rvm: "2.4.2", gemfile: "gemfiles/Gemfile.rails-4.0.x" }
    - { rvm: "2.5.0", gemfile: "gemfiles/Gemfile.rails-4.2.x" }
    - { rvm: "2.5.0", gemfile: "gemfiles/Gemfile.rails-4.1.x" }
    - { rvm: "2.5.0", gemfile: "gemfiles/Gemfile.rails-4.0.x" }
addons:
  apt:
    packages:
      - haveged
      - libgmp-dev
script: bundle exec rake spec
