sudo: required
dist: trusty
language: ruby
before_install:
  - gem update --system --no-doc
  - gem install bundler --no-doc
  - gem update bundler --no-doc
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
gemfile:
  - gemfiles/Gemfile.rails-5.2.x
  - gemfiles/Gemfile.rails-5.1.x
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-4.2.x
matrix:
  exclude:
    # Rails < 5 not on MRI 2.4+
    - { rvm: "2.4.5", gemfile: "gemfiles/Gemfile.rails-4.2.x" }
    - { rvm: "2.5.3", gemfile: "gemfiles/Gemfile.rails-4.2.x" }
addons:
  apt:
    packages:
      - haveged
      - libgmp-dev
script: bundle exec rake spec
