sudo: required
dist: trusty
language: ruby
before_install:
  - gem update --system --no-doc
  - gem install bundler --no-doc
  - gem update bundler --no-doc
rvm:
  - ruby-head
  - "2.7"
  - "2.6"
  - "2.5"
gemfile:
  - gemfiles/Gemfile.rails-6.0.x
  - gemfiles/Gemfile.rails-5.2.x
env:
  - TEST_TASK=spec
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - { rvm: "2.6",   gemfile: "Gemfile", env: [TEST_TASK=rubocop] }
addons:
  apt:
    packages:
      - haveged
      - libgmp-dev
script: bundle exec rake $TEST_TASK
