language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
gemfile:
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-3.1.x
  - gemfiles/Gemfile.rails-3.0.x
notifications:
  email:
    - pilots@errplane.com
  on_success: change
  on_failure: always
script: bundle exec rake spec
