---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spot-termination-handler
  namespace: default
rules:
- apiGroups:
  - "apps"
  resources:
  - "daemonsets"
  verbs:
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spot-termination-handler
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spot-termination-handler
  namespace: default
subjects:
- kind: ServiceAccount
  name: spot-termination-handler
  namespace: default
roleRef:
  kind: ClusterRole
  name: spot-termination-handler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: spot-termination-handler
  namespace: default
spec:
  selector:
    matchLabels:
      app: spot-termination-handler
  template:
    metadata:
      labels:
        app: spot-termination-handler
    spec:
      serviceAccountName: spot-termination-handler
      containers:
      - name: spot-termination-handler
        image: amazon/aws-node-termination-handler:v1.0.0
        imagePullPolicy: Always
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SPOT_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      nodeSelector:
        lifecycle: Ec2Spot
