version: 2.1

references:
  images:
    ubuntu: &UBUNTU_IMAGE ubuntu-1604:201903-01

jobs:
  test:
    machine:
      image: *UBUNTU_IMAGE
    parameters:
      ruby-version:
        type: string
      vault-version:
        type: string
    steps:
      - checkout
      - run:
          name: Install vault
          command: |
            curl -sLo vault.zip https://releases.hashicorp.com/vault/<< parameters.vault-version >>/vault_<< parameters.vault-version >>_linux_amd64.zip
            unzip vault.zip
            mkdir -p ~/bin
            mv vault ~/bin
            export PATH="~/bin:$PATH"
      - run:
          name: Run tests
          command: |
            export VAULT_VERSION=<< parameters.vault-version >>
            rvm use << parameters.ruby-version >> --install --binary --fuzzy
            bundle install --jobs=3 --retry=3 --path=vendor/bundle
            bundle exec rake

workflows:
  run-tests:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["2.2", "2.3", "2.4"]
              vault-version: ["1.0.3", "1.1.5", "1.2.4", "1.3.0"]
          name: test-ruby-<< matrix.ruby-version >>-vault-<< matrix.vault-version >>
