apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezkonnect-ui
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ezkonnect-ui
  template:
    metadata:
      labels:
        app: ezkonnect-ui
      annotations:
        logz.io/skip: "true"
    spec:
      containers:
        - name: ezkonnect-ui-container
          image: "{{ .Values.ezkonnectUi.image.repository }}:{{ .Values.ezkonnectUi.image.tag }}"
          ports:
            - containerPort: {{ .Values.ezkonnectUi.ports.http }}
          env:
            - name: VITE_ENDPOINT_API
              value: "http://{{ .Values.ezkonnectServer.service.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.ezkonnectServer.service.port }}"