{{- range $name, $roleBinding := .Values.rbac.roleBindings }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $roleBinding.roleRef.name }}
subjects: {{ toYaml $roleBinding.subjects | nindent 2 }}
{{- end }}
