{{ if .Values.enabled}}
{{- if eq .Values.mode "daemonset" -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "logs-collector.fullname" . }}
  namespace: {{ template "logs-collector.namespace" . }}
  labels:
    {{- include "logs-collector.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "logs-collector.selectorLabels" . | nindent 6 }}
      {{- include "logs-collector.component" . | nindent 6 }}
  updateStrategy:
    {{- if eq .Values.rollout.strategy "RollingUpdate" }}
    {{- with .Values.rollout.rollingUpdate }}
    rollingUpdate:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    type: {{ .Values.rollout.strategy }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-agent.yaml") . | sha256sum }}
        {{- include "logs-collector.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "logs-collector.selectorLabels" . | nindent 8 }}
        {{- include "logs-collector.component" . | nindent 8 }}
        {{- include "logs-collector.podLabels" . | nindent 8 }}
    spec:
      {{- $podValues := deepCopy .Values }}
      {{- $podData := dict "Values" $podValues "configmapSuffix" "-daemonset" "isAgent" true }}
      {{- include "logs-collector.loggingPod" ($podData | mustMergeOverwrite (deepCopy .)) | nindent 6 }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{ end }}
