# Default values for ezkkonect.

kubernetesInstrumentor:
  serviceAccount: "kubernetes-instrumentor"
  image:
    repository: "logzio/instrumentor"
    tag: "v1.0.5"
  instrumentationDetectorImage:
    repository: "logzio/instrumentation-detector"
    tag: "v1.0.5"
  javaAgentImage:
    repository: "logzio/otel-agent-java"
    tag: "v1.0.4"
  dotnetAgentImage:
    repository: "logzio/otel-agent-dotnet"
    tag: "v1.0.4"
  nodejsAgentImage:
    repository: "logzio/otel-agent-nodejs"
    tag: "v1.0.4"
  pythonAgentImage:
    repository: "logzio/otel-agent-python"
    tag: "v1.0.4"
  ports:
    metricsPort: 8080
    healthProbePort: 8081
  resources:
    limits:
      cpu: "500m"
      memory: "128Mi"
    requests:
      cpu: "10m"
      memory: "64Mi"
  env:
    monitoringServiceEndpoint: "logzio-monitoring-otel-collector.monitoring.svc.cluster.local"
  service:
    name: "kubernetes-instrumentor-service"
    port: 8080
    targetPort: 8080

ezkonnectServer:
  serviceAccount: "ezkonnect-server"
  image:
    repository: "logzio/ezkonnect-server"
    tag: "v1.0.6"
  ports:
    http: 8080
  service:
    name: "ezkonnect-server"
    port: 5050
    targetPort: 5050

ezkonnectUi:
  image:
    repository: "logzio/ezkonnect-ui"
    tag: "v0.0.5"
  ports:
    http: 31032
  service:
    name: "ezkonnect-ui"
    port: 31032
    targetPort: 31032

rbac:
  clusterRoles:
    kubernetesInstrumentor:
      rules:
        - apiGroups: [""]
          resources: ["pods", "pods/status"]
          verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
        - apiGroups: ["apps"]
          resources: ["deployments", "deployments/finalizers", "deployments/status", "statefulsets", "statefulsets/finalizers", "statefulsets/status"]
          verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
        - apiGroups: ["logz.io"]
          resources: ["instrumentedapplications", "instrumentedapplications/finalizers", "instrumentedapplications/status"]
          verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
    ezkonnectServer:
      rules:
        - apiGroups: ["", "logz.io", "apps"]
          resources: ["pods", "services", "instrumentedapplications", "deployments", "statefulsets"]
          verbs: ["get", "list", "watch", "update"]

  roles:
    logzioLeaderElectionRole:
      rules:
        - apiGroups: [""]
          resources: ["configmaps", "events"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
        - apiGroups: ["coordination.k8s.io"]
          resources: ["leases"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
