{{- if and .Values.metrics.enabled .Values.traces.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: { .Values.spanMetricsAggregator.name }
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.standaloneCollector.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "opentelemetry-collector.selectorLabels" . | nindent 6 }}
      component: standalone-collector
  template:
    metadata:
      labels:
        {{- include "opentelemetry-collector.selectorLabels" . | nindent 8 }}
        component: standalone-collector
        {{- with .Values.standaloneCollector.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
        {{- toYaml . | nindent 2 }}
        {{- end }}
        serviceAccountName: {{ include "opentelemetry-collector.serviceAccountName" . }}
        securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 2 }}
        containers:
        - name: {{ .Chart.Name }}
            command:
            - /{{ .Values.command.name }}
            - --config=/conf/relay.yaml
            {{- range .Values.command.extraArgs }}
            - {{ . }}
            {{- end }}
            securityContext:
            {{- toYaml .Values.securityContext | nindent 6 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.traces.enabled }}
            ports:
            {{- range $key, $port := .Values.spanMetricsAgregator.ports }}
            {{- if $port.enabled }}
            - name: {{ $key }}
                containerPort: {{ $port.containerPort }}
                protocol: {{ $port.protocol }}
                {{- if and $.isAgent $port.hostPort }}
                hostPort: {{ $port.hostPort }}
                {{- end }}
            {{- end }}
            {{- end }}
        {{- end }}
            env:
            - name: MY_POD_IP
                valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: status.podIP
            - name: LOGZIO_AGENT_VERSION
                value: {{.Chart.Version}}
            - name: REALESE_NAME
                value: {{.Release.Name}}
            - name: REALESE_NS
                value: {{.Release.Namespace}}
            - name: LISTENER_URL
                valueFrom:
                secretKeyRef:
                    name: logzio-secret
                    key: logzio-metrics-listener
            - name: P8S_LOGZIO_NAME
                valueFrom:
                secretKeyRef:
                    name: logzio-secret
                    key: p8s-logzio-name
            - name: SPM_TOKEN
                valueFrom:
                secretKeyRef:
                    name: logzio-secret
                    key: logzio-spm-shipping-token
            - name: ENV_ID
                valueFrom:
                secretKeyRef:
                    name: logzio-secret
                    key: env_id
            livenessProbe:
            httpGet:
                path: /
                port: 13133
            readinessProbe:
            httpGet:
                path: /
                port: 13133
            resources:
            {{- toYaml .Values.spanMetricsAgregator.resources | nindent 6 }}
            volumeMounts:
            - mountPath: /conf
                name: {{ .Chart.Name }}-configmap
        {{- if .Values.priorityClassName }}
        priorityClassName: {{ .Values.priorityClassName | quote }}
        {{- end }}
        volumes:
        - name: {{ .Chart.Name }}-configmap
            configMap:
            name: {{ include "opentelemetry-collector.fullname" . }}{{ .configmapSuffix }}
            items:
                - key: relay
                path: relay.yaml
        {{- with .Values.linuxNodeSelector }}
        nodeSelector:
        {{- toYaml . | nindent 2 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
        {{- toYaml . | nindent 2 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
        {{- toYaml . | nindent 2 }}
        {{- end }}
        {{- end}}