
apiVersion: v1
kind: Secret
metadata:
  name: logzio-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  env_id: {{.Values.secrets.env_id}}
{{- if .Values.metrics.enabled }}
  logzio-metrics-shipping-token: {{ .Values.secrets.MetricsToken }}
{{- end }}
{{- if or (eq .Values.metrics.enabled true) (eq .Values.spm.enabled true) }}
  logzio-metrics-listener: {{ .Values.secrets.ListenerHost }}
  p8s-logzio-name: {{.Values.secrets.p8s_logzio_name}}
{{- end }}
{{- if .Values.traces.enabled }}
  logzio-traces-shipping-token: {{ .Values.secrets.TracesToken }}
  logzio-listener-region: {{ .Values.secrets.LogzioRegion}}
  sampling-latency: {{ .Values.secrets.SamplingLatency | quote }}
  sampling-probability: {{ .Values.secrets.SamplingProbability | quote}}
{{ if .Values.spm.enabled }}
  logzio-spm-shipping-token: {{ .Values.secrets.SpmToken }}
{{ end }}
{{- end }}
{{- if .Values.secrets.windowsNodeUsername }}
{{- if .Values.secrets.windowsNodePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: logzio-windows-exporter-installer-secrets
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{.Values.secrets.windowsNodeUsername}}
  password: {{.Values.secrets.windowsNodePassword}}
{{- end }}
{{- end }}
