apiVersion: {{ .Values.apiVersions.daemonset }}
kind: DaemonSet
metadata:
  name: {{.Values.k8sApp}}
  labels:
    k8s-app: {{ .Values.k8sApp }}
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Values.k8sApp }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.k8sApp }}
        version: v1        
    spec:
      containers:
        - name: {{ .Values.k8sApp }}
          image:  "{{ .Values.image }}:{{ .Values.imageTag }}"
          env:
            - name: LOGZIO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{.Values.secretName}}
                  key: logzio-log-shipping-token
            - name: LOGZIO_LISTENER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: logzio-log-listener
            - name: ENV_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: env-id                  
      {{- if .Values.isRBAC }}
      serviceAccount: {{ template "logzio-k8s-events.serviceAccountName" . }}
      serviceAccountName: {{ template "logzio-k8s-events.serviceAccountName" . }}
      {{- end }}