{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "logzio-k8s-events.serviceAccountName" . }}
  labels:
    k8s-app: {{ .Values.k8sApp }}
    {{- include "logzio-k8s-events.labels" . | nindent 4 }}
{{- end }}
