---
# Creates a new GitHub release if the version in .version changed in the main branch.
name: create-tag

on:
  push:
    branches:
      - main
    paths:
      - .version

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        run: |
          APM_AGENT_JAVA_VERSION="v$(cat .version)"
          gh release create "${APM_AGENT_JAVA_VERSION}" \
            --title="${APM_AGENT_JAVA_VERSION}" \
            --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
      
